main:main.o BinarySearch.o BinaryRecursionSearch.o
	g++ -o main main.o BinarySearch.o BinaryRecursionSearch.o
main.o:BinarySearch.h BinaryRecursionSearch.o
BinarySearch.o:BinarySearch.h
BinaryRecursionSearch.o:BinaryRecursionSearch.h
